node {
  catchError {
    def maven = 'Maven 3.3'
    def java = 'Java Oracle 8'
    stage('Release') {
      withMaven(jdk: java, maven: maven) {
        // checkout the project
        deleteDir()
        git credentialsId: 'cacc0467-7c85-41d1-bf4e-eaa470dd5e59', poll: false, url: 'https://github.com/Silverpeas/Silverpeas-Jackrabbit-JCA.git'

        // identify the version
        def pom = readMavenPom()
        def version = pom.properties['next.release']
        if (pom.properties['silverpeas-jca.version'].contains('build') || pom.properties['silverpeas-jca.version'].contains('SNAPSHOT')) {
          error("The Silverpeas JCR AccessControl dependency must be a stable version for this project to be released. Current version is ${pom.properties['silverpeas-jca.version']}")
        }

        // release the project
        releaseProject('master', version)
      }
    }
  }
  step([$class: 'Mailer',
        notifyEveryUnstableBuild: true,
        recipients: "miguel.moquillon@silverpeas.org",
        sendToIndividuals: true])
}

def buildMavenProjectRelease(version) {
  sh """
mvn -U versions:set -DgenerateBackupPoms=false -DnewVersion=${version}
mvn clean deploy -Dmaven.test.skip=true -Prelease-sign-artifacts
"""
}

def releaseProject(commit, version) {
  echo "-> Release project to version ${version}"
  // we first change the Maven repo definition to use the repo dedicated to releases
  // then we release the project and finally we tag it
  sh """
git checkout ${commit}
git checkout -b release-${version}
"""
  buildMavenProjectRelease(version)
  sh """
git commit -am "Release of ${version}"
git tag ${version}
git push origin --tags
git push origin master
"""
}
