package builds.install

node {
  catchError {
    def gitRepo = 'https://github.com/mmoqui/Silverpeas-installation-tests.git'
    def build
    docker.image("silverpeas/silverbuild")
        .inside('-u root -v $HOME/.m2/settings.xml:/root/.m2/settings.xml -v $HOME/.m2/settings-security.xml:/root/.m2/settings-security.xml -v $HOME/.gitconfig:/root/.gitconfig -v $HOME/.ssh:/root/.ssh -v $HOME/.gnupg:/root/.gnupg') {
      stage('Preparation') {
        sh "rm -rf *"
        copyArtifacts projectName: 'Silverpeas_Master_AutoDeploy', flatten: true
        def lastBuild = readYaml file: 'build.yaml'
        build = lastBuild.version
        git poll: false, url: "${gitRepo}"
      }
      stage('Silverpeas Installation Test') {
        sh "bin/test-silverpeas-install ${build}"
      }
      stage('Silverpeas Update Test') {
        sh "bin/test-silverpeas-update ${build}"
      }
    }
  }
step([$class                  : 'Mailer',
      notifyEveryUnstableBuild: true,
      recipients              : "miguel.moquillon@silverpeas.org, yohann.chastagnier@silverpeas.org",
      sendToIndividuals       : true])
}

