package push.project

import java.util.regex.Matcher

node {
  catchError {
    def remoteUrl = 'https://github.com'
    def remote = [:]
    docker.image('silverpeas/silverbuild').inside('-u root -v $HOME/.m2/settings.xml:/root/.m2/settings.xml -v $HOME/.m2/settings-security.xml:/root/.m2/settings-security.xml -v $HOME/.gitconfig:/root/.gitconfig -v $HOME/.ssh:/root/.ssh -v $HOME/.gnupg:/root/.gnupg') {
      stage('Preparation') {
        def payload = new groovy.json.JsonSlurper().parseText(params.payload)
        remote.url = "${remoteUrl}/${payload.repository.owner.login}"
        remote.repository = payload.repository.name
        Matcher matcher = payload.ref =~ /^refs\\/heads\\/([a-zA-Z0-9.\-]+)$/
        remote.branch = matcher.matches() ? matcher.group(1) : payload.ref
        remote.defaultBranch = params.branch
        echo "Build of ${remote.url}/${remote.repository}:${remote.branch} asked!"
      }
      stage('Silverpeas Dependencies') {
        fetchRemoteSource(remote, 'silverpeas-dependencies-bom')
        sh "mvn clean install"
      }
      stage('Silverpeas Test Dependencies') {
        fetchRemoteSource(remote, 'silverpeas-dependencies-bom')
        sh "mvn clean install"
      }
      stage('Silverpeas Project') {
        fetchRemoteSource(remote, 'silverpeas-project')
        sh "mvn clean install"
      }
    }
  }
  step([$class                  : 'Mailer',
        notifyEveryUnstableBuild: true,
        recipients              : "miguel.moquillon@silverpeas.org, yohann.chastagnier@silverpeas.org, nicolas.eysseric@silverpeas.org",
        sendToIndividuals       : true])
}

def fetchRemoteSource(remote, repo) {
  sh 'rm -rf *'
  try {
    git credentialsId: 'cacc0467-7c85-41d1-bf4e-eaa470dd5e59', branch: remote.branch, poll: false, url: "${remote.url}/${repo}"
    return true
  } catch (Exception e) {
    // case the branch doesn't exist in the current remote repository.
    git credentialsId: 'cacc0467-7c85-41d1-bf4e-eaa470dd5e59', branch: remote.defaultBranch, poll: false, url: "${remote.url}/${repo}"
    return false
  }
}